### ISSUE TITLE
Update the list of publications and restructure the menu

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#19]
"Community/NExSS publications needs the now running list of publications that Dan Larsen is emailing out to the NExSS mailing list each month (2 weeks?). So instead of just White Papers being a link off of NExSS Publications, there should also be a link to Publications as well."

I think we might need clarification from the Jedi

**Comment by jlnoviello** [comment]
It sounds like this will be ingesting from the publications bulletin and putting it on the website in the Publications section on the homepage. Unfortunately, we've learned Dan Larsen will be leaving NExSS and so there is now a big question of who is going to take over this task. We'll have to discuss this at the meeting.

**Comment by danielapai** [comment]
For this, we will probably end up deciding to build a NExSS publication list through the NASA ADS system. Once this exists, we should link to that from the website.

**Comment by ajacksonastro** [comment]
We had previously discussed pulling a list directly from the NASA ADS system, which could be as simple as searching the acknowledgements for "NExSS", e.g. https://ui.adsabs.harvard.edu/search/p_=0&q=ack%3A%22NExSS%22&sort=date%20desc%2C%20bibcode%20desc

**Comment by andyburnett** [comment]
Linking directly to ADS will definitely be possible, but not immediately. However, we do have some options, and they may actually be better than ingesting the ADS feed.

1. We have added a new menu item to the Publications menu entitled "NExSS on ADS". It links directly to the ADS page, and effectively gives us what we are looking for.
2. In addition, it might be interesting to add papers (as they are published) to the NExSS twitter feed. I certainly get many of my paper alerts via twitter.

What do you think about the menu item? Does the name make sense?

**Comment by jlnoviello** [comment]
I actually really like the direct link to the ADS, since it's what many people in our field use. I'm sure the geologists who don't use ADS will start to use it if we can show them "look at the cool science that's over here!" 

I'm supposed to be adding papers to the Twitter feed but I've been so behind on social media posts lately. SCWG is also taking a break so I haven't been asking for help in running the account. Once classes end I'm hoping we can all come up for air and start adding little things like Twitter back onto our plates.

**Comment by andyburnett** [comment]
OK, in that case let's go with the direct menu link, and we can think about Twitter at a latter date.
