### ISSUE TITLE
SCWG: Content from SCWG at some point (Jessica?)  I know that Kevin Wagner (who is also one of my NHFP Sagan Fellows) just had a press release

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/nexss#20]

**Comment by jlnoviello** [comment]
I think this will end up being the archive for the Newsletters and Science Nuggets that are no longer on the front page

**Comment by andyburnett** [comment]
I think it is fine either way. Just let us know what content you want to appear under the heading.

**Comment by jlnoviello** [comment]
Okay, in that case I'd like this to have sections where the past Newsletters and Science Nuggets are listed (just their title and the link, we can add more detail later) and links to the Twitter and YouTube accounts

Twitter: https://twitter.com/nexssinfo
YouTube: https://www.youtube.com/channel/UCb0gqdGHntaPKxEuvc88Irg/featured

**Comment by andyburnett** [comment]
@jlnoviello I know this is a bit of a pain, but in the interests of clarity, do you think you could sketch out exactly what you have in mind? Just email me the picture whenever you have a moment.

**Comment by jlnoviello** [comment]
I am so sorry I forgot about this. I've done a quick sketch-up of what it looks like in my head when I think of the SCWG page. The Newsletter part will have to be adapted as we move to a more digital format, but I do want a record of the previous Newsletters we've done, since those were a lot of work! I think that when we get the blog format set-up, we can move that to where the "NExSS Newsletters" section is in this drawing, where all of the links underneath are individual stories rather than the static newsletters. Our current thinking is we will keep static Newsletters and start the blogs, so the static ones will just be aggregates of the most interesting pieces on the blog. We haven't done this yet so I'm not actually sure what will happen!


![IMG_5109](https://user-images.githubusercontent.com/13666168/116412230-7ae38a00-a804-11eb-8e37-1ba6d5b46e8b.JPG)

**Comment by jlnoviello** [comment]
Here are the Twitter and YouTube pictures to use for the sketch above. For the pictures and bios that will go in the Team Members section, I might need to ask everyone for those. We did them in the beginning when we first got started but I know some people have updated information and we all might want different pictures now. 

<img width="598" alt="Screen Shot 2021-04-28 at 9 44 46 AM" src="https://user-images.githubusercontent.com/13666168/116414744-b97a4400-a806-11eb-8e25-ccaa2089e853.png">
<img width="623" alt="Screen Shot 2021-04-28 at 9 45 44 AM" src="https://user-images.githubusercontent.com/13666168/116414746-ba12da80-a806-11eb-84d8-f4d9b67f44af.png">

**Comment by ajacksonastro** [comment]
The newsletters and science nuggets already have their own dedicated pages under Communications, which I think is where they should stay.  The SCWG page, in my mind, should have a list of the team members and talk about what SCWG does.  That includes obviously writing the newsletters and making science nuggets, but I don't think there is a need to duplicate those pages, we can just have links from the SCWG page to the newsletter and science nugget pages.

**Comment by jlnoviello** [comment]
Closing this because the content is now on the website
