### ISSUE TITLE
Adjust the content structure of the Working Groups

### ISSUE THREAD

**Issue by jlnoviello** [Knowinnovation/nexss#44]
I'm not quite sure what the correct technical phrase is for this, but the issue is how the information on the working groups is categorized within WordPress. The NExSS Leads do not like that the information is "hidden" within a post in the working group page. The information should be front and center, like it is on the ExoSS page (https://big10ideas.com/exoss-synergy/). 

I have no idea if this is just me putting the content in the wrong place or if the structure of how the working groups pages is set up, but the working groups' pages need to be changed to be more like the ExoSS page.

**Comment by ajacksonastro** [comment]
The difference is you want the information in a Page rather than a Post.  You can create pages, but you will need someone from KnowInnovation to link it in the correct location.

**Comment by andyburnett** [comment]
@jlnoviello That's no problem. Please take a look at what we did with the Science Communication WG. We have made it a hybrid so you can have descriptive text, and also still include items that you have written as blog style posts. We can remove the blog entries if all you want to do is have static pages, but perhaps the combination is useful?

**Comment by andyburnett** [comment]
Great. All links have been converted to this hybrid format. All you have to do is decide what content you want to appear on the page. You can find the pages just by searching for their title (having clicked the page link in the editor menu, rather than the posts link). If you don't create an categorised posts, the footer of each page won't show anything, but if you do want to add blog-like content, just create a post, and add the appropriate category.
